# python scripts/data/authenticate.py
hydra:
  job:
    chdir: True    # change to output folder

repo_id: "bezzam/DigiCam-Mirflickr-MultiMask-25K"
# repo_id: "bezzam/DigiCam-Mirflickr-MultiMask-1K"
# repo_id: "bezzam/DigiCam-Mirflickr-MultiMask-10K"
split: all   # "all" (for 100 masks), "test" (for 15 masks)
n_files: 100   # per mask
grayscale: True
torch_device: cuda:0
save_idx: [1, 2, 4, 5, 9]

font_scale: 1.5   # for plotting confusion matrix

metric: "recon"   # "recon", "mse", "lpips"

# Dataset parameters
huggingface:
  repo: "bezzam/DigiCam-Mirflickr-MultiMask-25K"
  psf: null   # null for simulating PSF
  image_res: [900, 1200]  # used during measurement
  rotate: True   # if measurement is upside-down
  flipud: False
  flip_lensed: False   # if rotate or flipud is True, apply to lensed
  alignment:
    top_left: [80, 100]  # height, width
    height: 200
  downsample: 1

# Simulation parameters for PSF
simulation:
  use_waveprop: True
  deadspace: True
  scene2mask: 0.3
  mask2sensor: 0.002

# Model parameters
algo: admm
# algo: "hf:digicam:mirflickr_multi_25k:Unet4M+U5+Unet4M_wave",
# algo: "hf:digicam:mirflickr_multi_25k:Unet4M+U5+Unet4M_wave_aux1",

# learned model parameters
# -- algo: "hf:camera:dataset:model"
inv_output: False   # use output of camera inversion instead of post-processor

# admm parameters
# -- algo: admm
n_iter: 25

# continue from previous run
cont: null     # continue already started file
scores_fp: null    # file path to already computed scores
