# python scripts/eval/benchmark_recon.py
#Hydra config
hydra:
  run:
    dir: "benchmark/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  job:
    chdir: True

device: "cuda"
# numbers of iterations to benchmark
n_iter_range: [5, 10, 20, 50, 100, 200, 300]
# number of files to benchmark
n_files: 200    # null for all files
#How much should the image be downsampled
downsample: 2
#algorithm to benchmark
algorithms: ["ADMM", "ADMM_Monakhova2019", "FISTA"] #["ADMM", "ADMM_Monakhova2019", "FISTA", "GradientDescent", "NesterovGradientDescent"]

# baseline from Monakhova et al. 2019, https://arxiv.org/abs/1908.11502
baseline: "MONAKHOVA 100iter"

save_idx: [0, 1, 2, 3, 4]   # provide index of files to save e.g. [1, 5, 10]

# Hyperparameters
nesterov:
  p: 0
  mu: 0.9
fista:
  tk: 1
admm:
  mu1: 1e-6
  mu2: 1e-5
  mu3: 4e-5
  tau: 0.0001