# #############################################################################
# benchmark.yaml
# =========
# Authors :
# Yohann PERRON  [yohann.perron@gmail.com]
# #############################################################################

#Config files for benchmark_recon.py

#Hydra config
hydra:
  run:
    dir: "benchmark/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  job:
    chdir: True

# numbers of iterations to benchmark
n_iter_range: [5, 10, 30, 60, 100, 200, 300]
# number of files to benchmark
n_files: 200
#How much should the image be downsampled
downsample: 8
#algorithm to benchmark
algorithms: ["ADMM", "FISTA", "GradientDescent", "NesterovGradientDescent"]

