# python scripts/eval/benchmark_recon.py -cn benchmark_diffusercam_mirflickr
defaults:
  - benchmark
  - _self_

dataset: HFDataset
batchsize: 4
device: "cuda:3"

huggingface:
  repo: "bezzam/DiffuserCam-Lensless-Mirflickr-Dataset-NORM"
  psf: psf.tiff
  image_res: null
  rotate: False   # if measurement is upside-down
  alignment: null
  downsample: 2
  downsample_lensed: 2
  flipud: True
  flip_lensed: True 
  single_channel_psf: True

algorithms: [
  # "ADMM",

  # ## - -- reconstructions trained on DiffuserCam
  # "hf:diffusercam:mirflickr:U5+Unet8M",
  # "hf:diffusercam:mirflickr:TrainInv+Unet8M",
  # "hf:diffusercam:mirflickr:MMCN4M+Unet4M",
  # "hf:diffusercam:mirflickr:MWDN8M",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M",
  # "hf:diffusercam:mirflickr:Unet4M+TrainInv+Unet4M",
  # "hf:diffusercam:mirflickr:Unet2M+MMCN+Unet2M",
  # "hf:diffusercam:mirflickr:Unet2M+MWDN6M",
  # "hf:diffusercam:mirflickr:Unet4M+U10+Unet4M",
  
  # ## - -- reconstructions trained on other datasets/systems
  # # "hf:tapecam:mirflickr:Unet4M+U10+Unet4M",
  # # "hf:digicam:mirflickr_single_25k:Unet4M+U5+Unet4M_wave",
  # # "hf:digicam:celeba_26k:Unet4M+U5+Unet4M_wave",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U10+Unet4M_wave",
  "hf:tapecam:mirflickr:Unet4M+U5+Unet4M_flips",
]

save_idx: [0, 1, 3, 4, 8]
n_iter_range: [100]    # for ADMM

