# python scripts/eval/benchmark_recon.py -cn benchmark_digicam_mirflickr_single
defaults:
  - benchmark
  - _self_


dataset: HFDataset
batchsize: 4
device: "cuda:0"

huggingface:
  repo: "bezzam/DigiCam-Mirflickr-SingleMask-25K"
  psf: null   # null for simulating PSF
  image_res: [900, 1200]  # used during measurement
  rotate: True   # if measurement is upside-down
  flipud: False
  flip_lensed: False   # if rotate or flipud is True, apply to lensed
  alignment:
    top_left: [80, 100]  # height, width
    height: 200
  downsample: 1

algorithms: [
  ## - simulated PSF (simulation.use_waveprop=True, simulation.deadspace=True)
  "hf:digicam:mirflickr_single_25k:U10_wave",
  "hf:digicam:mirflickr_single_25k:Unet8M_wave",
  "hf:digicam:mirflickr_single_25k:TrainInv+Unet8M_wave",
  "hf:digicam:mirflickr_single_25k:U10+Unet8M_wave",
  "hf:digicam:mirflickr_single_25k:Unet4M+TrainInv+Unet4M_wave",
  "hf:digicam:mirflickr_single_25k:Unet4M+U10+Unet4M_wave"

  ## -- below models need to set correct PSF simulation
  # ## - measured PSF (huggingface.psf=psf_measured.png)
  # "hf:digicam:mirflickr_single_25k:Unet4M+U10+Unet4M_measured",
  # ## - simulated PSF (simulation.use_waveprop=True, simulation.deadspace=False)
  # "hf:digicam:mirflickr_single_25k:Unet4M+U10+Unet4M_wave_nodead",
  # ## - simulated PSF (simulation.use_waveprop=False, simulation.deadspace=True)
  # "hf:digicam:mirflickr_single_25k:Unet4M+U10+Unet4M",
  # ## - simulated PSF (simulation.use_waveprop=False, simulation.deadspace=False)
  # "hf:digicam:mirflickr_single_25k:Unet4M+U10+Unet4M_nodead"
]
save_idx: [1, 2, 4, 5, 9]

# simulating PSF
simulation:
  use_waveprop: True
  deadspace: True
  scene2mask: 0.3
  mask2sensor: 0.002
