# python scripts/eval/benchmark_recon.py -cn benchmark_multilens_mirflickr_ambient
defaults:
  - benchmark
  - _self_

dataset: HFDataset
batchsize: 4
device: "cuda:0"

huggingface:
  repo: Lensless/MultiLens-Mirflickr-Ambient-25K
  cache_dir: /dev/shm
  psf: psf.png
  image_res: [600, 600]  # used during measurement
  rotate: False   # if measurement is upside-down
  alignment:
    top_left: [118, 220]  # height, width
    height: 123
  use_background: True

## -- reconstructions trained with same dataset/system
algorithms: [
  "ADMM",
]

save_idx: [1, 2, 4, 5, 9]
n_iter_range: [100]    # for ADMM
