sensor: rpi_hq
legacy: True   # Legacy image capture software (raspistill) or new one (libcamera)
bayer: True    # whether to capture Bayer data, otherwise directly capture RGB (demosaiced) data
nbits_bayer: 16   # output bit depth for Bayer data (16 or 8), only used if legacy=True
fn: test
exp: 0.5
config_pause: 2
sensor_mode: "0"   # {'off': 0, 'auto': 1, 'sunlight': 2, 'cloudy': 3, 'shade': 4, 'tungsten': 5, 'fluorescent': 6, 'incandescent': 7, 'flash': 8, 'horizon': 9}
iso: 100
awb_gains: null

# -- only one of below should be set
down: null  # downsample from maximum resolution
res: null   # desired resolution

# -- below only used if bayer=True, capture Bayer data but return as RGB or grayscale
rgb: False
gray: False
nbits_out: 8