# python scripts/recon/admm.py -cn diffusercam_mirflickr_single_admm
defaults:
  - defaults_recon
  - _self_


display:
  gamma: null

input:
  # File path for recorded PSF
  psf: data/DiffuserCam_Test/psf.tiff
  # File path for raw data  
  data: data/DiffuserCam_Test/diffuser/im5.npy
  dtype: float32
  original: data/DiffuserCam_Test/lensed/im5.npy

torch: True
torch_device: 'cuda:0'

preprocess:
  downsample: 8   # factor for PSF, which is 4x resolution of image
  normalize: False

admm:
  # Number of iterations
  n_iter: 20
  # Hyperparameters
  mu1: 1e-6
  mu2: 1e-5
  mu3: 4e-5
  tau: 0.0001
  #Loading unrolled model
  unrolled: True
  # checkpoint_fp: pretrained_models/Pre_Unrolled_Post-DiffuserCam/model_weights.pt
  checkpoint_fp: outputs/2023-09-11/22-06-49/recon.pt  # pre unet and post drunet
  pre_process_model: 
    network : UnetRes  # UnetRes or DruNet or null
    depth : 2 # depth of each up/downsampling layer. Ignore if network is DruNet
  post_process_model: 
    network : DruNet  # UnetRes or DruNet or null
    depth : 2 # depth of each up/downsampling layer. Ignore if network is DruNet
  