# python scripts/recon/train_unrolled.py -cn fine-tune_PSF
defaults:
  - train_unrolledADMM
  - _self_

#Trainable Mask
trainable_mask:
  mask_type: TrainablePSF #Null or "TrainablePSF"
  initial_value: "DiffuserCam" # "random" or "DiffuserCam" or "DiffuserCam_gray"
  mask_lr: 1e-3
  L1_strength: 1.0  #False or float
  use_mask_in_dataset : False # Work only with simulated dataset

#Training
training:
  epoch: 50
  save_every: 5

display:
  gamma: 2.2
