# python scripts/recon/train_learning_based.py -cn fine-tune_PSF
defaults:
  - train_unrolledADMM
  - _self_

#Trainable Mask
trainable_mask:
  mask_type: TrainablePSF
  initial_value: psf
  mask_lr: 1e-3
  L1_strength: 1.0  #False or float

#Training
training:
  save_every: 1   # to see how PSF evolves

display:
  gamma: 2.2
