# python scripts/recon/dataset.py
defaults:
  - defaults_recon
  - _self_

torch: True
torch_device: 'cuda:0'

repo_id: "bezzam/DiffuserCam-Lensless-Mirflickr-Dataset"
split: "test"    # "train", "test", "all"
psf_fn: "psf.png"    # in repo root
output_folder: null  # autocreate name if not spe
n_files: 25    # null for all files

preprocess:
  flip_ud: True 
  flip_lr: False
  downsample: 6
  # to have different data shape than PSF
  data_dim: null

algo: admm   # "admm", "apgd", "null" to just copy over (resized) raw data
admm:
  n_iter: 100
apgd:  
  n_jobs: 1    # run in parallel as algo is slow
  max_iter: 500

# extraction region of interest
roi: null   # top, left, bottom, right

display:
  disp: -1
  plot: False
