# python scripts/recon/dataset.py
defaults:
  - defaults_recon
  - _self_

torch: True
torch_device: 'cuda:0'

dataset: diffusercam
split: test    # "train", "test", "all"
downsample: 2
data_dim: null
output_folder: null  # autocreate name if not specified
n_files: 25    # null for all files

algo: admm   # "admm", "apgd", "null" to just copy over (resized) raw data
admm:
  n_iter: 100
apgd:  
  n_jobs: 1    # run in parallel as algo is slow
  max_iter: 500

# extraction region of interest
roi: null   # top, left, bottom, right

display:
  disp: -1
  plot: False
