# python scripts/recon/digicam_mirflickr.py
defaults:
  - defaults_recon
  - _self_

cache_dir: null
metrics_fp : null
hf_repo: null    # by default use one in model config

# set model
# -- for learning-based methods (comment if using ADMM)
model: Unet4M+U5+Unet4M_wave

# # -- for ADMM with fixed parameters
# model: admm
# n_iter: 10

device: cuda:1
save_idx: [1, 2, 4, 5, 9]
n_files: null
percent_pixels_wrong: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
flip: True   # whether to flip mask values (True) or reset them (False)