# python scripts/recon/train_learning_based.py -cn train_mirflickr_tape_ambient
defaults:
  - train_mirflickr_tape
  - _self_

wandb_project:
device_ids:

# Dataset
files:
  dataset: Lensless/TapeCam-Mirflickr-Ambient
  image_res: [600, 600]

alignment:
  # when there is no downsampling
  top_left: [80, 180]  # height, width
  height: 190
