# python scripts/recon/train_unrolled.py -cn train_psf_from_scratch
defaults:
  - train_unrolledADMM
  - _self_

#Trainable Mask
trainable_mask:
  mask_type: TrainablePSF #Null or "TrainablePSF"
  initial_value: "random" # "random" or "DiffuserCam" or "DiffuserCam_gray"

# Train Dataset
files:
  dataset: "CelebA"   # Simulated : "mnist", "fashion_mnist", "cifar10", "CelebA". Measure :"DiffuserCam"
