# python scripts/recon/train_learning_based.py -cn train_mirflickr_tape_ambient_learned_sub
defaults:
  - train_mirflickr_tape
  - _self_

wandb_project: tapecam_ambient
device_ids: [0, 1 ,2, 3]
torch_device: cuda:0

# Dataset
files:
  #n_files: 10
  dataset: Lensless/TapeCam-Mirflickr-Ambient   # 16K examples
  #dataset: Lensless/TapeCam-Mirflickr-Ambient-100   # 100 examples
  cache_dir: /dev/shm
  image_res: [600, 600]

reconstruction:
  # one or the other
  direct_background_subtraction: False
  learned_background_subtraction: [4, 8, 16, 32]   # 127740 parameters, False to turn off
  integrated_background_subtraction: False

  pre_process:   ## Targeting 3923428 parameters
    network : UnetRes  # UnetRes or DruNet or null
    depth : 4 # depth of each up/downsampling layer. Ignore if network is DruNet
    nc: [32,64,112,128]

alignment:
  # when there is no downsampling
  top_left: [85, 185]  # height, width
  height: 178

optimizer:
  type: AdamW
  cosine_decay_warmup: True
