# python scripts/recon/train_unrolled.py -cn train_unrolled_multimask
defaults:
  - train_unrolledADMM
  - _self_


torch_device: 'cuda:0'
device_ids: [0, 1, 2, 3]

# Dataset
files:
  dataset: bezzam/DigiCam-Mirflickr-MultiMask-10K
  huggingface_dataset: True
  downsample: 1
  image_res: [900, 1200]  # used during measurement
  rotate: True   # if measurement is upside-down

alignment:
  # when there is no downsampling
  topright: [80, 100]  # height, width
  height: 200

training:
  batch_size: 4
  epoch: 25
  eval_batch_size: 16

