# python scripts/recon/train_unrolled.py -cn train_unrolled_multimask
defaults:
  - train_unrolledADMM
  - _self_

# Dataset
files:
  dataset: bezzam/DigiCam-Mirflickr-MultiMask-1K
  huggingface_dataset: True
  downsample: 1.6
  image_res: [900, 1200]  # used during measurement
  rotate: True   # if measurement is upside-down

alignment:
  # when there is no downsampling
  topright: [80, 100]  # height, width
  height: 200

training:
  batch_size: 4
  epoch: 25
  eval_batch_size: 10

