# python scripts/recon/train_unrolled.py -cn train_multilens_array
defaults:
  - train_unrolledADMM
  - _self_

# Train Dataset
files:
  dataset: fashion_mnist   # Simulated : "mnist", "fashion_mnist", "cifar10", "CelebA". Measure :"DiffuserCam"
  celeba_root: /scratch/bezzam
  downsample: 16     # TODO use simulation instead?   
  n_files: 50

torch_device: "cuda" 

#Trainable Mask
trainable_mask:
  mask_type: TrainableMultiLensArray
  optimizer: Adam
  mask_lr: 1e-3
  L1_strength: False
  binary: False
  initial_value:
    N : 10 #TODO: check this value ? 
    psf_wavelength: [550e-9]
    design_wv: 550e-9

simulation:
  grayscale: True
  flip: False
  scene2mask: 40e-2
  mask2sensor: 2e-3
  sensor: "rpi_hq"
  downsample: 16
  object_height: 0.30

training:
  crop_preloss: False # crop region for computing loss
  batch_size: 2
  epoch: 25
  eval_batch_size: 16
  save_every: 1
