# python scripts/recon/train_learning_based.py -cn train_digicam_multimask
defaults:
  - train_digicam_singlemask
  - _self_

torch_device: 'cuda:0'
device_ids: [0, 1, 2, 3]
eval_disp_idx: [1, 2, 4, 5, 9]

# Dataset
files:
  dataset: bezzam/DigiCam-Mirflickr-MultiMask-25K

  extra_eval: 
    singlemask: 
      huggingface_repo: bezzam/DigiCam-Mirflickr-SingleMask-25K
      display_res: [900, 1200]  # used during measurement
      rotate: True   # if measurement is upside-down
      alignment:
        topright: [80, 100]  # height, width
        height: 200
