# python scripts/recon/train_unrolled.py -cn train_pre-post-processing
defaults:
  - train_unrolledADMM
  - _self_

reconstruction:
  method: unrolled_admm

  pre_process:
    network: UnetRes
    depth: 2
  post_process:
    network: DruNet
    depth: 4

training:
  epoch: 50
  crop_preloss: False

optimizer:
  slow_start: 0.01

loss: l2
lpips: 1.0
