# python scripts/data/upload_diffusercam_huggingface.py
hydra:
  job:
    chdir: True    # change to output folder

repo_id: "bezzam/DiffuserCam-Lensless-Mirflickr-Dataset"
dir_diffuser: "/scratch/bezzam/DiffuserCam_mirflickr/dataset/diffuser_images"
dir_lensed: "/scratch/bezzam/DiffuserCam_mirflickr/dataset/ground_truth_lensed"
psf_fp: "data/psf/diffusercam_psf.tiff"
hf_token: null
file_ext: ".npy"
n_files: null
n_jobs: 4     # for parallelizing conversion to PNG